export default {
  pages: [
    'pages/index/index',
    'pages/button/index',
    'pages/flex/index',
    'pages/white-space/index',
    'pages/wing-blank/index',
    'pages/drawer-base/index',
    'pages/drawer/index',
    'pages/menu/index',
    'pages/navbar/index',
    'pages/pagination/index',
    'pages/popover/index',
    'pages/segmented-control/index',
    'pages/tabbar/index',
    'pages/tabbar/demo-0/index',
    'pages/tabbar/demo-1/index',
    'pages/tabs/index',
    'pages/accordion/index',
    'pages/badge/index',
    'pages/card/index',
    'pages/grid/index',
    'pages/carousel/index',
    'pages/icon/index',
    'pages/list/index',
    'pages/notice-bar/index',
    'pages/steps/index',
    'pages/tag/index',
    'pages/checkbox/index',
    'pages/radio/index',
    'pages/input/index',
    'pages/stepper/index',
    'pages/search-bar/index',
    'pages/activity-indicator/index',
    'pages/progress/index',
    'pages/result/index',
    'pages/locale-provider/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}
